### ISSUE TITLE
comment count on loader button

### ISSUE THREAD

**Issue by columbian-chris** [Joel-James/disqus-conditional-load#19]
Is there a way to display the number of comments in the "Load Comments" button when plugin is set to load disqus on click?

**Comment by Joel-James** [comment]
Hey @columbian-chris,

That is a feature available in the Pro version. You can see more details [here](https://dclwp.com/).

**Comment by columbian-chris** [comment]
Sorry, I missed that one when I perused the page.  Appreciate the reply.
