### ISSUE TITLE
Intermittent issues when minifying page HTML output

### ISSUE THREAD

**Issue by dryanmedia** [joel-james/disqus-conditional-load#2]
Not an issue with your plugin, per se, but a heads up.

When running HTML minification on page output using a plugin or other method, due to two inline JavaScript comments, _occasional_ JavaScript errors present that prevent DISQUS from loading due to lack of EOL.

https://github.com/joel-james/disqus-conditional-load/blob/master/public/dcl-functions.php#L48

https://github.com/joel-james/disqus-conditional-load/blob/master/public/dcl-functions.php#L52

**Comment by joel-james** [comment]
@dryanmedia Thanks for the heads up :+1: Will fix this though next version.

**Comment by joel-james** [comment]
Please update and check.
