### ISSUE TITLE
wp 4.5.3 Cannot redeclare dsq_options()

### ISSUE THREAD

**Issue by emanresusername** [joel-james/disqus-conditional-load#5]
on wp v`4.5.3` i get the following error when trying to activate this plugin

```text
Plugin could not be activated because it triggered a fatal error.

Fatal error: Cannot redeclare dsq_options() (previously declared in /var/www/html/wp-content/plugins/disqus-comment-system/disqus.php:30) in /var/www/html/wp-content/plugins/disqus-conditional-load/disqus-core/disqus.php on line 38
```

**Comment by joel-james** [comment]
Hi @emanresusername 

Please do not activate this plugin along with Disqus official plugin. It is mentioned in our installation doc also. If you are using this plugin, you don't have to use official Disqus plugin anymore. Please deactivate it and try again.

**Comment by emanresusername** [comment]
oh, thanks, wasn't sure if it worked instead of or in addition to, my bad 😅

**Comment by joel-james** [comment]
Yea. Confusion! I think we will have to rewrite the plugin description :yum:

**Comment by emanresusername** [comment]
well you were absolutely right, it was right at the top of the installation doc. but the description tab is the one it shows first on the homepage and the `view details` popup and I just stopped there . . . [software dev would be great if it weren't for the users 😅](https://www.youtube.com/watch?v=HSS8tiy9Y3U)
